# Práctica 2.

## Diccionarios

Escribir un programa que almacene las calificaciones de un semestre en el diccionario {'Electromagnetismo': 10, 'Electrónica': 9, 'Relatividad': 8,'Física Computacional': 10, 'Física Estadística': 9,} y después muestre por pantalla las calificaciones de cada asignatura en el formato *asignatura* como Key y *calificacion* como valor del Key. Al final debe mostrar también el promedio del semestre.


In [2]:
#Ejemplo
peso_atomico = {} #diccionario vacío
peso_atomico['H'] = 1
peso_atomico['He'] = 2
peso_atomico['Cl'] = 35.5
#print(peso_atomico)


#Tu código
calificaciones = {}
calificaciones['fisica computacional'] = int(input('Dime tu calificación en física computacional: '))
calificaciones['mecanica analitica'] = int(input('Dime tu califiación en mecánica analítica: '))
calificaciones['termodinamica'] = int(input('Dime tu calificación en termodinámica: '))
calificaciones['relatividad'] = int(input('Dime tu calificación en relatividad: '))
print(calificaciones)


Dime tu calificación en física computacional: 10
Dime tu califiación en mecánica analítica: 9
Dime tu calificación en termodinámica: 8
Dime tu calificación en relatividad: 8
{'fisica computacional': 10, 'mecanica analitica': 9, 'termodinamica': 8, 'relatividad': 8}


In [3]:
def promedio(l):
    n=len(l)
    s=0
    for i in range(n):
        s+=l[i]
    return s/n

#for i in keys: keys es una lista de strings y aquí se va iterando entre los strings de esa lista

keys = ['fisica computacional','mecanica analitica','termodinamica','relatividad']
calif = []
for i in range(len(keys)):
    calif.append(calificaciones.get(keys[i]))
    
print('El promedio de este semestre es: ',promedio(calif),'con las siguientes calificaciones',calificaciones)

El promedio de este semestre es:  8.75 con las siguientes calificaciones {'fisica computacional': 10, 'mecanica analitica': 9, 'termodinamica': 8, 'relatividad': 8}


## Programa básico de Python

Un satélite se encuentra en una órbita circular alrededor de la Tierra, tal que completa un círculo en $T$ segundos, $T$ es el periodo de la órbita:

i) Muestra que la altitud $h$ sobre la superficie de la Tierra será:
$$
h=\left( \frac{GMT^2}{4\pi^2} \right)^{\tfrac{1}{3}} -R
$$
donde $G$ es la constante de gravitación universal con valor $G=6.67\times10^{-11}$ m$^{3}$kg$^{-1}$s$^{-2}$, $M$ es la masa de la Tierra $M=5.97\times10^{24}$kg y $R$ es el radio de la Tierra $R=6371$ kg.

(ii) Escribe un programa que le pregunte al usuario el periodo que desea tenga su satélite girando alrededor de la Tierra y el programa le regrese la altitud, en metros, que deberá tener.

(iii) ¿Qué altitud deberá tener el satélite su queremos que orbite la Tierra con un periodo de un día (órbita geosíncrona), 90 minutos, 45 minutos? ¿Qué observas?

(iv) En práctica, una órbita geosíncrona es aquella cuya órbita tiene un periodo de un día sideral, que es de 23.93 horas, no de 24 horas. ¿Por qué es esto? ¿Cuál será la diferencia en altitud entre $T$= 23.93 horas y $T$= 24 horas.


In [4]:
#Inciso i pendiente

In [6]:
# Tu código
#Inciso ii
import math as mth
G = 6.67e-10
M = 5.97e24
R = 6371e3
def altitud(periodo):
    return ((G*M*T**2)/4*mth.pi**2)**(1/3)-R

T = float(input('Dime el periodo en segundos que quieres que tenga tu satélite: '))
print('La altitud de tu satélite será',altitud(T),'metros')

Dime el periodo en segundos que quieres que tenga tu satélite: 5569.79
La altitud de tu satélite será 60927572.726923406 metros


In [7]:
#Inciso iii
def segundos(días,minutos):
    s_días = días*24*60*60 #Convertimos días a segundos
    s_minutos = minutos*60 #Convertimos minutos a segundos
    s_total = s_días + s_minutos 
    return s_total

T = segundos(1,90) + 45
print('La altitud del satélite será',altitud(T),'metros')

La altitud del satélite será 429626151.62827915 metros


In [8]:
#Inciso iii
T1 = segundos(0,23.93) #día sideral
T2 = segundos(0,24) #día común
h1 = altitud(T1)
h2 = altitud(T2)
print('La altitud de un día sideral es',h1,'metros','mientras que la altitud de un día terrestre es',h2,'metros')

La altitud de un día sideral es 429626151.62827915 metros mientras que la altitud de un día terrestre es 429626151.62827915 metros


## Matriz de Vandermonde

Considera la matriz de Vandermonde, la cual se define como

$$
A_{ij} = v_i^{j} \;\;\; i=0,1,2, \cdots, n; \;\;\; j=0,1,2,\cdots, n
$$

Crea una función llamada *Vandermonde(v)* que reciba un vector $\vec{v}$ y regrese la matriz A definida arriba.


In [2]:
# Tu código
import numpy as np
v = []
n = int(input('Dame la longitud de tu vector v: '))
A = np.empty([n,n],float)
for i in range(n):
    v.append(float(input('Dame el valor %d-ésimo del vector: '%i)))

def Vandermonde(vector):
    for i in range(len(vector)):
        for j in range(len(vector)):
            A[i,j] = v[i]**j
    return A
Vandermonde(v)

Dame la longitud de tu vector v: 3
Dame el valor 0-ésimo del vector: 1
Dame el valor 1-ésimo del vector: 2
Dame el valor 2-ésimo del vector: 3


array([[1., 1., 1.],
       [1., 2., 4.],
       [1., 3., 9.]])

## Matriz tridiagonal

Crea una función llamada tridiagonal que reciba un vector y regrese la matriz cuadrada

$$
A=
\begin{bmatrix}
v_{0} & v_{1}^2 & 0 &  0 & 0 & \dots  & 0 \\
v_{1}^3 & v_{1} & v_{2}^2 &  0 & 0 & \dots  & 0 \\
0 & v_{2}^3 & v_2 &  v_{3}^2 & 0 & \dots  & 0 \\
0 & 0 & v_3^2 &  v_{3} & v_4^2 & \dots  & 0 \\
\dots & \dots  & \dots & \dots & \dots & \dots & \dots\\
0 & 0 & 0 & \dots & v_{n-1}^3 & v_{n-1}  & v_{n}^2 \\
0 & 0 & 0 & 0 & \dots & v_{n}^3  & v_{n} \\
\end{bmatrix}
$$


Prueba con varios vectores e incluye estos vectores en tu código.



In [46]:
#Tu código
def genera_vector():
    v = []
    n = int(input('Dame la longitud de tu vector v: '))
    for i in range(n):
        v.append(float(input('Dame el valor %d-ésimo del vector: '%i)))
    return v
        

def genera_matriz_zeros(vector):
    n = len(vector)
    A = np.zeros([n,n],float)
    return A

def tridiagonal(vector):
    A = genera_matriz_zeros(vector)
    for i in range(len(vector)): #Iteramos renglones
        for j in range(len(vector)): #Iteramos columnas
            if j==i:
                A[i,j] = v[i] #Diagonal
            if 0 <= i-1 and j == i-1:
                A[i,j] = v[i]**3
            elif i-1<len(vector) and i == j-1:
                A[i,j] = v[i+1]**2
    return A

In [47]:
tridiagonal([1,2,3])

array([[ 1.,  4.,  0.],
       [ 8.,  2.,  9.],
       [ 0., 27.,  3.]])

In [50]:
tridiagonal([2,4,6,8,10])

array([[  1.,   4.,   0.,   0.,   0.],
       [  8.,   2.,   9.,   0.,   0.],
       [  0.,  27.,   3.,  16.,   0.],
       [  0.,   0.,  64.,   4.,  25.],
       [  0.,   0.,   0., 125.,   5.]])

In [51]:
tridiagonal([1,2,3,4,5])

array([[  1.,   4.,   0.,   0.,   0.],
       [  8.,   2.,   9.,   0.,   0.],
       [  0.,  27.,   3.,  16.,   0.],
       [  0.,   0.,  64.,   4.,  25.],
       [  0.,   0.,   0., 125.,   5.]])

### Matriz de Pauli

Las matrices de Pauli son muy populares en Mecánica Cuántica. Se sabe que para una partícula con espín $\tfrac{1}{2}$, como es el electrón, las matrices de Pauli tienen la siguiente forma:

\begin{equation*}
\sigma_x=
\begin{bmatrix}
0&1\\
1&0
\end{bmatrix} \hspace{0.5cm}
\sigma_y=\begin{bmatrix}
0&-i\\
i&0
\end{bmatrix} \hspace{0.5cm}
\sigma_z=\begin{bmatrix}
1&0\\
0&-1
\end{bmatrix}
\end{equation*}

Haz una función llamada *Pauli* que reciba el eje y regrese la matriz de Pauli correspondiente, es decir, escribas *mx=Pauli('x')* y regrese $\sigma_x$.


In [61]:
# Tu código
sigma_x = np.array([[0,1],[1,0]])
sigma_y = np.array([[0,-1j],[1j,0]])
sigma_z = np.array([[1,0],[0,-1]])
def Pauli(eje):
    if eje == 'x':
        matriz = sigma_x
    elif eje == 'y':
        matriz = sigma_y
    elif eje == 'z':
        matriz == sigma_z
    return matriz

Pauli('y')

array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]])

## Propiedades de las matrices de Pauli

Haremos 3 funciones para comprobar las propiedades más importantes de las matrices de Pauli.

* $\sigma_x^2=\sigma_y^2=\sigma_z^2=\begin{bmatrix}
1&0\\
0&1
\end{bmatrix}$.

Haz una función llamada *matriz\_al\_cuadrado*, que reciba una matriz y regrese su matriz al cuadrado. Ya que tengas tu función, prueba con las 3 matrices de Pauli, generadas en el problema anterior. Hint: Puedes reciclar el código de multiplicación de matrices.

* $Tr(\sigma_i)=0$.

Haz una función llamada traza que reciba una matriz y regrese su traza. Recuerda que la traza de una matriz cuadrada es la suma de los elementos de la diagonal.

* $det(\sigma_i)=-1.$

Haz una función que calcule el determinante de una matriz. Hint: Puedes usar el comando *numpy.linalg.det(M)*, importando *import numpy.linalg* para comprobar el determinante obtenido por tu código.

In [52]:
# Tu código
